name: LevelNull
description: Just a placeholder site for levelnull.org

# Plugins from the whitelist at https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb
#plugins:
#  - jekyll-theme-tactile

#theme: jekyll-theme-tactile

# website address
url: https://levelnull.org/

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'CNAME'
    - 'node_modules'

github:
    is_project_page: true
    repository_name: 'levelnull.org'
    repository_url: 'https://github.com/levelnull/levelnull.org'
    owner_url: 'https://github.com/levelnull'
    owner_name: 'LevelNull'

show_downloads: false
